version: '3.1'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: searcher
      POSTGRES_USER: searcher
      POSTGRES_PASSWORD: 123

  postgres-test:
    image: postgres:11
    environment:
      POSTGRES_DB: searcher-test
      POSTGRES_USER: searcher-test
      POSTGRES_PASSWORD: 123
    ports:
      - 5433:5432

  redis:
    image: redis:5.0.5
    container_name: redis
    ports:
      - 6379:6379
