version: '3.1'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: searcher
      POSTGRES_USER: searcher
      POSTGRES_PASSWORD: 123

  redis:
    image: redis:5.0.5
    container_name: redis
    ports:
      - 6379:6379
