apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: searcher
            - name: POSTGRES_USER
              value: searcher
            - name: POSTGRES_PASSWORD
              value: 123
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "searcher-pgdata"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: searcher-pgdata